#!/usr/bin/env bash
source functions/update.sh
source functions/upgrade.sh
source functions/add-repo.sh
source functions/install-package.sh
source functions/clean.sh

source scripts/defaults.sh
source scripts/ppas.sh

# initialize
source scripts/init.sh

# install packages available in default archive
for i in "${packagesDefault[@]}"; do install-package $i; done

# add 3rd party archives
for i in "${ppas[@]}"; do add-repo $i; done
# update
update
# install packages from 3rd party archives
for i in "${packages[@]}"; do install-package $i; done

if [[ `lsb_release -cs` = "loki" ]]; then
  # add 3rd party loki archives
  for i in "${loki_ppas[@]}"; do add-repo $i; done
  # update
  update
  # install packages from 3rd party loki archives
  for i in "${loki_packages[@]}"; do install-package $i; done
fi

# execute custom installation scripts
source customs/virtualbox-5.sh
source customs/vagrant.sh
source customs/docker.sh
source customs/docker-compose.sh
source customs/pyenv.sh
source customs/rbenv.sh
source customs/exenv.sh
source customs/goenv.sh
source customs/nodenv.sh
source customs/zsh.sh
source customs/neovim.sh
source customs/add-getdeb-repo.sh
source customs/google-apps.sh

# update, upgrade, clean
update
upgrade
clean

echo 
echo "###############################################"
echo "# to install nvidia drivers execute:          #"
echo "# $ bash customs/nvidia.sh                    #"
echo "###############################################"
echo
